# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TRAVIS: 'true' # Skip tests requiring data
    strategy:
      matrix:
        python-version:
          - '3.10'
    name: Python ${{ matrix.python-version }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install gcc libffi-dev libssl-dev nodejs npm libyaml-dev libxslt1-dev

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          make api-deps
          make ui-deploy
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            coveralls
      - name: Unit tests
        run: |
          make tests

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit tests

      - name: Notify
        uses: Som-Energia/ghactions-notify@main
        if: failure()
        # this allows the build to succeed even when the notification fails
        # e.g. due to dependabot push, which may not have the secret
        continue-on-error: true
        with:
          webhook: ${{ secrets.WEBHOOK_ALERTES_WEBAPPS }}

      - name: Google Chat Notificationa
        uses: SimonScholz/google-chat-action@main
        if: failure()
        # this allows the build to succeed even when the notification fails
        # e.g. due to dependabot push, which may not have the secret
        continue-on-error: true
        with:
          # https://docs.github.com/en/webhooks/webhook-events-and-payloads
          webhookUrl: ${{ secrets.WEBHOOK_ALERTES_WEBAPPS }}
          jobStatus: ${{ job.status }}
          imageUrl: ${{ format('https://github.com/{0}.png', github.event.head_commit.author.username) }}
          imageAltText: ${{ github.event.head_commit.author.name }}
          subtitle: ${{ github.event.head_commit.message }}
          title: "${{ format('{0} -- [{1}]', github.event.repository.name, github.event.ref) }}"

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
